import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import Navigation from "@/components/Navigation";

export const metadata: Metadata = {
    title: {
        template: 'hrgn - %s',
        default: 'hrgn',
    },
    description: "Generated by create next app",
    authors: [{name: 'Frederik Hørgreen Sørensen'}],
    keywords: [
        "hrgn",
        "Frederik Hørgreen Sørensen",
        "portfolio",
        "enterprise architect",
        "hiper",
    ],
    robots: {index: true, follow: true}
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body
            className={``}
        >
        <Navigation />
        <div className="px-4">
            {children}
        </div>
        </body>
        </html>
    );
}
