services:
  web:
    image: registry.hrgn.dk/hrgn-dk:dev
    build:
      target: development
    volumes:
      - ./next:/src
    ports:
      - "3000:3000"
    environment:
      REACT_APP_VERSION: "development"
